spring.data.mongodb.uri=mongodb://localhost:27017/neuroxdb
spring.data.mongodb.database=neuroxdb
spring.data.mongodb.auto-index-creation=true
server.port=8080

# Gemini AI
gemini.api.key=your_api_key
